name: mybook
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  dartz: ^0.10.1
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  go_router: ^14.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: GT
      fonts:
        - asset: assets/fonts/GT Sectra Fine Regular.ttf
    - family: Po
      fonts:
        - asset: assets/fonts/PoetsenOne-Regular.ttf
