name: mybook
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  dartz: ^0.10.1
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  go_router: ^14.2.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: GT
      fonts:
        - asset: assets/fonts/GT Sectra Fine Regular.ttf
    - family: Po
      fonts:
        - asset: assets/fonts/PoetsenOne-Regular.ttf
